<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE it-customer [
    <!ELEMENT it-customer (customers)>
    <!ELEMENT customers (ID, name, lastname, gender, age, category)>
    
    <!ELEMENT ID (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT gender (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT category (#PCDATA)>

    <!ENTITY personal "บุคคลทั่วไป">
    <!ENTITY corp "บริษัท">
    <!ENTITY vip "VIP">
]>

<it-customer>
    <customers>
        <ID>2001</ID>
        <name>สมชาย</name>
        <lastname>ใสสะอาด</lastname>
        <gender>ชาย</gender>
        <age>32 ปี</age>
        <category>&corp;</category>
    </customers>
    <customers>
        <ID>2002</ID>
        <name>สมหญิง</name>
        <lastname>บุญมี</lastname>
        <gender>หญิง</gender>
        <age>35 ปี</age>
        <category>&personal;</category>
    </customers>
    <customers>
        <ID>2003</ID>
        <name>พันนิดา</name>
        <lastname>ทองดี</lastname>
        <gender>หญิง</gender>
        <age>20 ปี</age>
        <category>&vip;</category>
    </customers>
    <customers>
        <ID>2004</ID>
        <name>อริสา</name>
        <lastname>จิตดี</lastname>
        <gender>หญิง</gender>
        <age>19 ปี</age>
        <category>&personal;</category>
    </customers>
    <customers>
        <ID>2005</ID>
        <name>กษมา</name>
        <lastname>ทองมาก</lastname>
        <gender>หญิง</gender>
        <age>17 ปี</age>
        <category>&personal;</category>
    </customers>
</it-customer>